### ISSUE TITLE
When all elements are equal, the time complexity of sort512::sort is O(n^2).

### ISSUE THREAD

**Issue by platelett** [berenger-eu/avx-512-sort#1]

**Comment by berenger-eu** [comment]
Thanks for your feedback. Indeed, but I would suggest that those who might face such a configuration, they can perform a simple test on the array before calling the sort function (implementing a "is_sorted" with avx512 should be nice).
Otherwise, I would have to add the test inside the kernels, and everyone will pay the cost.
Actually there are works that have solutions which share many properties with avx-512-sort but manage many corner cases, and might interest others:
https://elib.dlr.de/142624/1/LIPIcs-SEA-2021-3.pdf
https://elib.dlr.de/145402/1/thesis_col.pdf
So I will close the issue, but I am open if someone wants to provide a "is_sorted" or the kernels with additional tests.
